apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfga
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://openfga.github.io/helm-charts
    chart: openfga
    targetRevision: latest
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/bratva-gzp/openfga/main/openfga-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openfga

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
