apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluid
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://github.com/coredgeio/ccs-helm-charts.git
    targetRevision: main   # or specific commit/tag
    path: .   # path to Helm chart (update if needed)
    helm:
      valueFiles:
        - values.yaml   # your modified values file

  destination:
    server: https://kubernetes.default.svc
    namespace: fluid

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
